# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import crawler_pb2 as crawler__pb2


class CrawlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDynamicInfo = channel.unary_unary(
                '/Crawler.Crawler/GetDynamicInfo',
                request_serializer=crawler__pb2.JsonRequest.SerializeToString,
                response_deserializer=crawler__pb2.JsonResponse.FromString,
                )


class CrawlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDynamicInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDynamicInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDynamicInfo,
                    request_deserializer=crawler__pb2.JsonRequest.FromString,
                    response_serializer=crawler__pb2.JsonResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Crawler.Crawler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Crawler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDynamicInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Crawler.Crawler/GetDynamicInfo',
            crawler__pb2.JsonRequest.SerializeToString,
            crawler__pb2.JsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
